version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "dme86"

  - package-ecosystem: 'bundler'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - "dme86"
